on: push

jobs:
  build-and-publish-to-cloud:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master
    
    - name: Publish to Talend Cloud
      uses: Talend/publish-to-cloud@master
      with:
        args: -e -am
        project: sfty_test
        updatesite_path: https://update.talend.com/Studio/8/updates/latest
        service_url: https://tmc.us.cloud.talend.com/inventory/
        cloud_token: ${{ secrets.CLOUD_TOKEN }}
        nexus_url: http://192.168.1.95:8081
        nexus_username: ${{ secrets.NEXUS_USERNAME }}
        nexus_password: ${{ secrets.NEXUS_PASSWORD }}
       # license_path: license.gpg
       # license_passphrase: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
